apiVersion: v1
kind: Service
metadata:
  name: controller-nodeport
  namespace: platform
spec:
  type: NodePort
  selector:
    app: controller
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: REPLACE_CONTROLLER_NODEPORT
