apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller-sa
      containers:
        - name: controller
          image: REPLACE_CONTROLLER_IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

            - name: ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: ADMIN_API_KEY
            - name: SITE_NODEPORT_START
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: SITE_NODEPORT_START
            - name: SITE_NODEPORT_END
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: SITE_NODEPORT_END
            - name: MAILCOW_API_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: MAILCOW_API_URL
            - name: MAILCOW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: MAILCOW_API_KEY
            - name: MAILCOW_VERIFY_TLS
              value: "true"
            - name: DB_HOST
              value: "postgres.infra.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_ADMIN_USER
              value: "postgres"
            - name: DB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: DB_ADMIN_PASSWORD
            - name: DB_NAME_PREFIX
              value: "db_"
            - name: DB_USER_PREFIX
              value: "u_"
