apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller-sa
      containers:
        - name: controller
          image: REPLACE_CONTROLLER_IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: TLS_ENABLED
              value: "false"
            - name: CERT_ISSUER_NAME
              value: "letsencrypt-staging"
            - name: ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: ADMIN_API_KEY
            - name: SITE_NODEPORT_START
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: SITE_NODEPORT_START
            - name: SITE_NODEPORT_END
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: SITE_NODEPORT_END
