apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller-sa
      containers:
        - name: controller
          image: REPLACE_CONTROLLER_IMAGE
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: backups
              mountPath: /backups
          env:
            - name: PORT
              value: "8080"

            - name: ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: ADMIN_API_KEY
            - name: SITE_NODEPORT_START
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: SITE_NODEPORT_START
            - name: SITE_NODEPORT_END
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: SITE_NODEPORT_END
            - name: MAILCOW_API_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: MAILCOW_API_URL
            - name: MAILCOW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: MAILCOW_API_KEY
            - name: MAILCOW_VERIFY_TLS
              value: "true"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: POSTGRES_PORT
            - name: POSTGRES_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: POSTGRES_ADMIN_USER
            - name: POSTGRES_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: POSTGRES_ADMIN_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: POSTGRES_DB
            - name: DB_NAME_PREFIX
              value: "db_"
            - name: DB_USER_PREFIX
              value: "u_"
      volumes:
        - name: backups
          hostPath:
            path: /backups
            type: DirectoryOrCreate
