apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: panel
  namespace: platform
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: REPLACE_PANEL_TLS_ISSUER
spec:
  tls:
    - hosts:
        - REPLACE_PANEL_DOMAIN
      secretName: tls-panel
  rules:
    - host: REPLACE_PANEL_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: panel
                port:
                  number: 3000
