apiVersion: v1
kind: Service
metadata:
  name: panel
  namespace: platform
spec:
  type: NodePort
  selector:
    app: panel
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: REPLACE_PANEL_NODEPORT
