apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-sa
  namespace: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","create","delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get","list","create","patch","update"]
  - apiGroups: [""]
    resources: ["limitranges"]
    verbs: ["get","list","create","patch","update"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get","list","create","patch","update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get","list","create","patch","update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-binding
subjects:
  - kind: ServiceAccount
    name: controller-sa
    namespace: platform
roleRef:
  kind: ClusterRole
  name: controller-role
  apiGroup: rbac.authorization.k8s.io
