apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: bind9-dns-tcp
  namespace: dns-zone
spec:
  entryPoints:
    - dns-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: bind9
          port: 53
