apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: bind9-dns-udp
  namespace: dns-zone
spec:
  entryPoints:
    - dns-udp
  routes:
    - services:
        - name: bind9
          port: 53
