apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-sa
  namespace: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-bootstrap
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","create","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-operator
rules:
  - apiGroups: [""]
    resources: ["services","configmaps","secrets","persistentvolumeclaims"]
    verbs: ["get","list","watch","create","patch","update","delete"]
  - apiGroups: [""]
    resources: ["resourcequotas","limitranges"]
    verbs: ["get","list","watch","create","patch","update","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","create","patch","update","delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses","networkpolicies"]
    verbs: ["get","list","watch","create","patch","update","delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["get","list","watch","create","patch","update","delete"]
  - apiGroups: ["batch"]
    resources: ["cronjobs","jobs"]
    verbs: ["get","list","watch","create","patch","update","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-bootstrap-binding
subjects:
  - kind: ServiceAccount
    name: controller-sa
    namespace: platform
roleRef:
  kind: ClusterRole
  name: controller-bootstrap
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-platform-secrets
  namespace: platform
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-platform-secrets-binding
  namespace: platform
subjects:
  - kind: ServiceAccount
    name: controller-sa
    namespace: platform
roleRef:
  kind: Role
  name: controller-platform-secrets
  apiGroup: rbac.authorization.k8s.io

