apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mailcow-deny-ingress
  namespace: mail-zone
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mailcow-allow-api-from-controller
  namespace: mail-zone
spec:
  podSelector:
    matchLabels:
      app: mailcow
      component: nginx
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: platform
          podSelector:
            matchLabels:
              app: controller
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mailcow-allow-ui-from-traefik
  namespace: mail-zone
spec:
  podSelector:
    matchLabels:
      app: mailcow
      component: nginx
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - traefik
                  - kube-system
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mailcow-allow-mail-from-traefik
  namespace: mail-zone
spec:
  podSelector:
    matchLabels:
      app: mailcow
    matchExpressions:
      - key: component
        operator: In
        values:
          - postfix
          - dovecot
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - traefik
                  - kube-system
      ports:
        - protocol: TCP
          port: 25
        - protocol: TCP
          port: 465
        - protocol: TCP
          port: 587
        - protocol: TCP
          port: 143
        - protocol: TCP
          port: 993
        - protocol: TCP
          port: 110
        - protocol: TCP
          port: 995
