- op: replace
  path: /spec/tls/0/hosts/0
  value: REPLACE_PANEL_DOMAIN
- op: replace
  path: /spec/rules/0/host
  value: REPLACE_PANEL_DOMAIN
- op: replace
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: REPLACE_PANEL_TLS_ISSUER
