apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-runner-role
  namespace: PLACEHOLDER_NAMESPACE
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch","create","patch","update","delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","patch"]
