apiVersion: v1
kind: Secret
metadata:
  name: panel-basicauth
  namespace: platform
type: Opaque
stringData:
  users: "REPLACE_PANEL_BASICAUTH"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: panel-auth
  namespace: platform
spec:
  basicAuth:
    secret: panel-basicauth
