apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: dns-tcp
  namespace: dns-zone
spec:
  entryPoints:
    - dns-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: bind9
          port: 53
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: dns-udp
  namespace: dns-zone
spec:
  entryPoints:
    - dns-udp
  routes:
    - services:
        - name: bind9
          port: 53
