apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-runner
  namespace: backup-zone
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-runner-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch","create","delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-runner-binding
subjects:
  - kind: ServiceAccount
    name: backup-runner
    namespace: backup-zone
roleRef:
  kind: ClusterRole
  name: backup-runner-role
  apiGroup: rbac.authorization.k8s.io
