apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-runner-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["pods","persistentvolumeclaims"]
    verbs: ["get","list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list"]
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-runner-binding
subjects:
  - kind: ServiceAccount
    name: backup-runner
    namespace: backup
roleRef:
  kind: ClusterRole
  name: backup-runner-role
  apiGroup: rbac.authorization.k8s.io
