apiVersion: v1
kind: Secret
metadata:
  name: mailcow-basicauth
  namespace: mail-zone
type: Opaque
stringData:
  users: "REPLACE_MAILCOW_BASICAUTH"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mailcow-auth
  namespace: mail-zone
spec:
  basicAuth:
    secret: mailcow-basicauth
