apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - dns-zone.yaml
  - flux-system.yaml
  - infra-db.yaml
  - kyverno.yaml
  - mail-zone.yaml
  - platform.yaml
