apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - networkpolicy.yaml
  - pgadmin-auth.yaml
  - pgadmin-deploy.yaml
  - pgadmin-ingress.yaml
  - pgadmin-secret.yaml
  - pgadmin-svc.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
