apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |
    ports:
      smtp:
        port: 25
        expose: true
        exposedPort: 25
        protocol: TCP
      smtps:
        port: 465
        expose: true
        exposedPort: 465
        protocol: TCP
      submission:
        port: 587
        expose: true
        exposedPort: 587
        protocol: TCP
      imap:
        port: 143
        expose: true
        exposedPort: 143
        protocol: TCP
      imaps:
        port: 993
        expose: true
        exposedPort: 993
        protocol: TCP
      pop3:
        port: 110
        expose: true
        exposedPort: 110
        protocol: TCP
      pop3s:
        port: 995
        expose: true
        exposedPort: 995
        protocol: TCP
      dns-tcp:
        port: 53
        expose: true
        exposedPort: 53
        protocol: TCP
      dns-udp:
        port: 53
        expose: true
        exposedPort: 53
        protocol: UDP