apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: panel
  namespace: platform
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: platform-panel-auth@kubernetescrd
    cert-manager.io/cluster-issuer: REPLACE_PANEL_TLS_ISSUER
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - REPLACE_PANEL_DOMAIN
      secretName: tls-panel
  rules:
    - host: REPLACE_PANEL_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: panel
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: panel-http-redirect
  namespace: platform
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: platform-panel-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: REPLACE_PANEL_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: panel
                port:
                  number: 3000