apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: panel-redirect
  namespace: platform
  labels:
    app.kubernetes.io/part-of: voxeil
spec:
  redirectScheme:
    scheme: https
    permanent: true
